"""empty message

Revision ID: 7b7010923de6
Revises: 
Create Date: 2019-01-13 09:39:09.599211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b7010923de6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_task', sa.Column('keyword', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_task', 'keyword')
    # ### end Alembic commands ###
