"""empty message

Revision ID: 8591c44c5633
Revises: 86125b43562c
Create Date: 2019-03-03 17:24:11.108413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8591c44c5633'
down_revision = '86125b43562c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('job_task_ibfk_1', 'job_task', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('job_task_ibfk_1', 'job_task', 'template', ['template'], ['id'])
    # ### end Alembic commands ###
