"""empty message

Revision ID: 86125b43562c
Revises: ce8062f6b3f2
Create Date: 2019-03-03 16:49:40.061205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86125b43562c'
down_revision = 'ce8062f6b3f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_task', sa.Column('template', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_task', 'template', ['template'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_task', type_='foreignkey')
    op.drop_column('job_task', 'template')
    # ### end Alembic commands ###
