"""empty message

Revision ID: ce8062f6b3f2
Revises: dea0e528d66a
Create Date: 2019-01-23 13:48:29.390101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8062f6b3f2'
down_revision = 'dea0e528d66a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('keyword_used', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'keyword_used')
    # ### end Alembic commands ###
