"""empty message

Revision ID: dbc7b23e7b6f
Revises: 477c8f28b683
Create Date: 2019-04-18 22:32:13.855780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbc7b23e7b6f'
down_revision = '477c8f28b683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_task', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_task', 'template', ['template_id'], ['id'])
    op.drop_constraint('template_ibfk_1', 'template', type_='foreignkey')
    op.drop_column('template', 'job_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('job_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('template_ibfk_1', 'template', 'job_task', ['job_id'], ['id'])
    op.drop_constraint(None, 'job_task', type_='foreignkey')
    op.drop_column('job_task', 'template_id')
    # ### end Alembic commands ###
