"""empty message

Revision ID: dea0e528d66a
Revises: 7b7010923de6
Create Date: 2019-01-16 20:36:47.935269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea0e528d66a'
down_revision = '7b7010923de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('campaign', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'campaign')
    # ### end Alembic commands ###
