"""empty message

Revision ID: bf3c038f77b8
Revises: 033d3c3ffe79
Create Date: 2020-01-13 17:08:16.904072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3c038f77b8'
down_revision = '033d3c3ffe79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape', sa.Column('meta', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape', 'meta')
    # ### end Alembic commands ###
